# Generated by Django 5.2.9 on 2026-01-04 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_score', models.IntegerField(default=0, help_text='Điểm tín dụng (0-1000)')),
                ('risk_level', models.CharField(choices=[('VERY_LOW', 'Rất thấp'), ('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('VERY_HIGH', 'Rất cao')], default='MEDIUM', max_length=15)),
                ('income_stability', models.FloatField(default=0, help_text='Độ ổn định thu nhập (0-100)')),
                ('debt_to_income_ratio', models.FloatField(default=0, help_text='Tỷ lệ nợ/thu nhập')),
                ('payment_history_score', models.FloatField(default=0, help_text='Điểm lịch sử thanh toán (0-100)')),
                ('ai_analysis', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, default=1000000, max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, default=100000000, max_digits=15)),
                ('min_interest_rate', models.FloatField(default=8.0, help_text='% Lãi suất tối thiểu mong muốn')),
                ('preferred_duration_min', models.IntegerField(default=1, help_text='Kỳ hạn tối thiểu (tháng)')),
                ('preferred_duration_max', models.IntegerField(default=24, help_text='Kỳ hạn tối đa (tháng)')),
                ('risk_tolerance', models.CharField(choices=[('LOW', 'Thấp - Chỉ cho vay hồ sơ tốt'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao - Chấp nhận rủi ro')], default='MEDIUM', max_length=10)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_returns', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active_investments', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lender_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_text', models.TextField(verbose_name='Nội dung hợp đồng')),
                ('signed_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_disputed', models.BooleanField(default=False)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_type', models.CharField(choices=[('LATE_PAYMENT', 'Chậm thanh toán'), ('WRONG_AMOUNT', 'Sai số tiền'), ('CONTRACT_VIOLATION', 'Vi phạm hợp đồng'), ('OTHER', 'Khác')], max_length=30)),
                ('description', models.TextField(help_text='Mô tả chi tiết tranh chấp')),
                ('status', models.CharField(choices=[('OPEN', 'Đang mở'), ('IN_REVIEW', 'Đang xem xét'), ('RESOLVED', 'Đã giải quyết'), ('ESCALATED', 'Đã chuyển lên cấp cao')], default='OPEN', max_length=20)),
                ('ai_analysis', models.TextField(blank=True, null=True)),
                ('ai_recommendation', models.TextField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_disputes', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='lending.loancontract')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.FloatField(help_text='% Lãi suất mong muốn/năm')),
                ('duration_months', models.IntegerField(help_text='Kỳ hạn (tháng)')),
                ('purpose', models.TextField(help_text='Mục đích vay (AI sẽ đọc cái này)')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ duyệt'), ('APPROVED', 'Đã duyệt sàn'), ('FUNDED', 'Đã giải ngân'), ('REJECTED', 'Bị từ chối')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loancontract',
            name='loan_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lending.loanrequest'),
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='lending.loancontract')),
            ],
        ),
    ]
