# Generated by Django 5.2.9 on 2026-01-04 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LenderMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0, help_text='Điểm phù hợp (0-100)')),
                ('match_reasons', models.JSONField(default=list, help_text='Lý do match')),
                ('is_notified', models.BooleanField(default=False)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_interested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_matches', to=settings.AUTH_USER_MODEL)),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='lending.loanrequest')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('loan_request', 'lender')},
            },
        ),
    ]
