# Generated by Django 5.2.9 on 2026-01-06 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_lendermatchresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='complainant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_filed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='dispute',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('FAVOR_COMPLAINANT', 'Có lợi cho người khiếu nại'), ('FAVOR_RESPONDENT', 'Có lợi cho bên bị khiếu nại'), ('COMPROMISE', 'Thỏa thuận'), ('DISMISSED', 'Bác bỏ')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loancontract',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrower_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loancontract',
            name='borrower_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loancontract',
            name='borrower_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loancontract',
            name='contract_content',
            field=models.TextField(blank=True, verbose_name='Nội dung chi tiết'),
        ),
        migrations.AddField(
            model_name='loancontract',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loancontract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loancontract',
            name='interest_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='loancontract',
            name='lender_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loancontract',
            name='lender_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loancontract',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loancontract',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loancontract',
            name='status',
            field=models.CharField(choices=[('PENDING_SIGNATURES', 'Chờ ký'), ('ACTIVE', 'Đang hoạt động'), ('COMPLETED', 'Hoàn thành'), ('DEFAULTED', 'Vỡ nợ'), ('CANCELLED', 'Đã hủy')], default='PENDING_SIGNATURES', max_length=20),
        ),
        migrations.AddField(
            model_name='loancontract',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loancontract',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='dispute_type',
            field=models.CharField(choices=[('PAYMENT', 'Vấn đề thanh toán'), ('LATE_PAYMENT', 'Chậm thanh toán'), ('WRONG_AMOUNT', 'Sai số tiền'), ('CONTRACT_TERMS', 'Điều khoản hợp đồng'), ('CONTRACT_VIOLATION', 'Vi phạm hợp đồng'), ('FRAUD', 'Gian lận'), ('OTHER', 'Khác')], max_length=30),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raised_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Đang mở'), ('IN_REVIEW', 'Đang xem xét'), ('RESOLVED', 'Đã giải quyết'), ('CLOSED', 'Đã đóng'), ('ESCALATED', 'Đã chuyển lên cấp cao')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='loancontract',
            name='contract_text',
            field=models.TextField(blank=True, verbose_name='Nội dung hợp đồng'),
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('SCREENSHOT', 'Ảnh chụp màn hình'), ('DOCUMENT', 'Tài liệu'), ('CHAT_LOG', 'Lịch sử chat'), ('PAYMENT_PROOF', 'Bằng chứng thanh toán'), ('OTHER', 'Khác')], max_length=20)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='dispute_evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='lending.dispute')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('late_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán'), ('OVERDUE', 'Quá hạn'), ('PARTIAL', 'Thanh toán một phần')], default='PENDING', max_length=15)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='lending.loancontract')),
            ],
            options={
                'ordering': ['contract', 'installment_number'],
                'unique_together': {('contract', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('DISBURSEMENT', 'Giải ngân'), ('INSTALLMENT', 'Trả góp kỳ hạn'), ('EARLY_PAYOFF', 'Trả trước hạn'), ('LATE_FEE', 'Phí trễ hạn'), ('REFUND', 'Hoàn tiền')], max_length=20)),
                ('payment_method', models.CharField(choices=[('WALLET', 'Ví điện tử'), ('BANK_TRANSFER', 'Chuyển khoản'), ('CARD', 'Thẻ')], default='WALLET', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Đang xử lý'), ('COMPLETED', 'Hoàn thành'), ('FAILED', 'Thất bại'), ('REFUNDED', 'Đã hoàn')], default='PENDING', max_length=15)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('late_days', models.IntegerField(default=0)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='lending.loancontract')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('payment_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lending.paymentschedule')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
