# Generated by Django 5.2.9 on 2026-01-04 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lending', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('BORROWER_PROFILER', 'Agent Borrower Profiler'), ('LENDER_MATCHER', 'Agent Lender Matcher'), ('CONTRACT_GENERATOR', 'Agent Contract Generator'), ('PAYMENT_MONITOR', 'Agent Payment Monitor'), ('DISPUTE_RESOLVER', 'Agent Dispute Resolver')], max_length=30)),
                ('input_data', models.JSONField(help_text='Dữ liệu đầu vào')),
                ('output_data', models.JSONField(blank=True, help_text='Kết quả xử lý', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Đang xử lý'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại')], default='PENDING', max_length=15)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PAYMENT_REMINDER', 'Nhắc thanh toán'), ('LOAN_APPROVED', 'Đơn vay được duyệt'), ('LOAN_REJECTED', 'Đơn vay bị từ chối'), ('LOAN_FUNDED', 'Đơn vay được giải ngân'), ('MATCH_FOUND', 'Tìm được người cho vay'), ('CONTRACT_READY', 'Hợp đồng đã sẵn sàng'), ('DISPUTE_UPDATE', 'Cập nhật tranh chấp'), ('KYC_STATUS', 'Trạng thái KYC')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LenderMatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text='Điểm phù hợp (0-100)')),
                ('match_reasons', models.JSONField(help_text='Lý do matching')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ phản hồi'), ('ACCEPTED', 'Đã chấp nhận'), ('REJECTED', 'Đã từ chối'), ('EXPIRED', 'Hết hạn')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to=settings.AUTH_USER_MODEL)),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='lending.loanrequest')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('loan_request', 'lender')},
            },
        ),
    ]
