# Generated by Django 5.2.9 on 2026-01-04 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agents', '0001_initial'),
        ('lending', '0002_lendermatchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='lending.loanrequest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PAYMENT_REMINDER', 'Nhắc thanh toán'), ('LOAN_APPROVED', 'Đơn vay được duyệt'), ('LOAN_REJECTED', 'Đơn vay bị từ chối'), ('LOAN_FUNDED', 'Đơn vay được giải ngân'), ('MATCH_FOUND', 'Tìm được người cho vay'), ('LOAN_MATCH', 'Khoản vay phù hợp'), ('CONTRACT_READY', 'Hợp đồng đã sẵn sàng'), ('DISPUTE_UPDATE', 'Cập nhật tranh chấp'), ('KYC_STATUS', 'Trạng thái KYC'), ('SYSTEM', 'Thông báo hệ thống')], max_length=30),
        ),
        migrations.DeleteModel(
            name='LenderMatchResult',
        ),
    ]
