# Generated by Django 5.2.9 on 2026-01-04 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='kyc_images/')),
                ('doc_type', models.CharField(choices=[('ID_CARD_FRONT', 'CCCD Mặt trước'), ('ID_CARD_BACK', 'CCCD Mặt sau'), ('SALARY_SLIP', 'Bảng lương/Sao kê')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ai_extracted_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('id_card_number', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('kyc_status', models.CharField(choices=[('UNVERIFIED', 'Chưa xác thực'), ('PENDING', 'Đang chờ AI duyệt'), ('VERIFIED', 'Đã xác thực'), ('REJECTED', 'Bị từ chối')], default='UNVERIFIED', max_length=20)),
                ('kyc_note', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
