# Generated by Django 5.2.9 on 2026-01-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='ocr_status',
            field=models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('PROCESSING', 'Đang xử lý'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tên công ty'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=10, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hometown',
            field=models.CharField(blank=True, max_length=255, verbose_name='Quê quán'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Thu nhập hàng tháng'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nghề nghiệp'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ocr_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Dữ liệu OCR từ CCCD'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ocr_match_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm khớp OCR (%)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ocr_verified',
            field=models.BooleanField(default=False, verbose_name='Đã verify OCR'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ thường trú'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Số CCCD'),
        ),
    ]
