# Generated by Django 5.2.9 on 2026-01-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_kycdocument_ocr_status_userprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='ocr_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Dữ liệu OCR'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='ocr_status',
            field=models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('PROCESSING', 'Đang xử lý'), ('COMPLETED', 'Hoàn thành'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại')], default='PENDING', max_length=20),
        ),
    ]
